name: pruebas

on:
  push:
    branches-ignore:
      - main
    branches:
      - "*"

jobs:
  primero:
    runs-on: ubuntu-latest
    permissions: #requeridos para pruebas de código, linters etc
      security-events: write
    steps:
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
