name: pruebas

on:
  push:
    branches-ignore:
      - main

jobs:
  primero:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHTOKEN }}
      - name: correr python lint
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
