name: pruebas

on:
  push:
    branches-ignore:
      - main

jobs:
  primero:
    runs-on: ubuntu-latest
    permissions: #requeridos para pruebas de código, linters etc
      security-events: write
    steps:
      - name: bajar codigo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHTOKEN }}
      - name: correccion
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
          token: ${{ secrets.GHTOKEN }}
